import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import TopNavbar from "../components/TopNavbar"
import UserNavbar from "../components/UserNavbar"
import Navbar from "../components/Navbar"
import Footer from '../components/Footer'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <header>
          {/* <TopNavbar /> */}
          <div className="w-full fixed top-0 left-0 z-50">
            <UserNavbar />
            <Navbar />
          </div>
        </header>
        <main className="max-w-7xl mx-auto px-4 lg:px-0 min-h-screen pt-40">
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
